/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_nano_nativetime_NativeTimeNoCritical */

#ifndef _Included_io_nano_nativetime_NativeTimeNoCritical
#define _Included_io_nano_nativetime_NativeTimeNoCritical
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_nano_nativetime_NativeTime
 * Method:    currentTimeMicros
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL
Java_io_nano_time_jni_NativeTimeNoCritical_currentTimeMicros(JNIEnv *, jobject);

/*
 * Class:     io_nano_nativetime_NativeTime
 * Method:    currentTimeNanos
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL
Java_io_nano_time_jni_NativeTimeNoCritical_currentTimeNanos(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
