sudo: false
language: java
jdk: openjdk8

cache:
    directories:
    - "$HOME/.m2"
script:
  - mvn --show-version install

deploy:
    provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
    skip_cleanup: true
    on:
        tags: true