sudo: false
language: java
jdk: openjdk8

cache:
    directories:
    - "$HOME/.m2"
script:
  - mvn --show-version install

deploy:
  -
    provider: bintray
    key: $BINTRAY_API_KEY
    user: nano-io
    skip_cleanup: true
    on:
        tags: true
