sudo: false
language: java
jdk: openjdk8

cache:
    directories:
    - "$HOME/.m2"
script:
  - mvn --show-version verify

deploy:
  -
    provider: script
    script: "mvn -s .travis.settings.xml deploy"
    skip_cleanup: true
    on:
        tags: true
